[tool.poetry]
name = "livraria"
version = "0.1.0"
description = ""
authors = ["ruddy"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.0.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
