# Generated by Django 4.0.5 on 2022-06-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Autores'),
        ),
        migrations.AlterField(
            model_name='catagoria',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Editora'),
        ),
    ]
