# Generated by Django 4.0.5 on 2022-06-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_autor_nome_alter_catagoria_descricao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagoria',
            options={'verbose_name': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='editor',
            options={'verbose_name': 'Editor'},
        ),
        migrations.AlterField(
            model_name='catagoria',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='editor',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
