# Generated by Django 4.0.5 on 2022-06-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_livro_editora_alter_livro_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='preco',
            field=models.FloatField(),
        ),
    ]
